name: My First GitHub Actions

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Check Python Version
        run: |
          python3 --version

      - name: Create Virtual Environment
        run: |
          python3 -m venv venv

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install pytest

      - name: Run Tests
        run: |
          source venv/bin/activate
          cd src
          pytest addition.py
