name: My First GitHub Actions

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Check Python Version
        run: |
          python3 --version
          pip3 --version

      - name: Install pytest
        run: |
          pip3 install pytest

      - name: Run tests
        run: |
          cd src
          pytest addition.py
